//>>built
require({cache:{"dojo/Deferred":function(){define(["./has","./_base/lang","./errors/CancelError","./promise/Promise","./promise/instrumentation"],function(h,l,e,f,a){var d=Object.freeze||function(){},b=function(b,g,q,e,a){2===g&&(m.instrumentRejected&&0===b.length)&&m.instrumentRejected(q,!1,e,a);for(a=0;a<b.length;a++)c(b[a],g,q,e)},c=function(b,g,q,e){var a=b[g],c=b.deferred;if(a)try{var d=a(q);if(0===g)"undefined"!==typeof d&&n(c,g,d);else{if(d&&"function"===typeof d.then){b.cancel=d.cancel;d.then(k(c,
1),k(c,2),k(c,0));return}n(c,1,d)}}catch(f){n(c,2,f)}else n(c,g,q);2===g&&m.instrumentRejected&&m.instrumentRejected(q,!!a,e,c.promise)},k=function(b,g){return function(a){n(b,g,a)}},n=function(b,g,a){if(!b.isCanceled())switch(g){case 0:b.progress(a);break;case 1:b.resolve(a);break;case 2:b.reject(a)}},m=function(a){var g=this.promise=new f,q=this,p,k,l,h=!1,n=[];Error.captureStackTrace&&(Error.captureStackTrace(q,m),Error.captureStackTrace(g,m));this.isResolved=g.isResolved=function(){return 1===
p};this.isRejected=g.isRejected=function(){return 2===p};this.isFulfilled=g.isFulfilled=function(){return!!p};this.isCanceled=g.isCanceled=function(){return h};this.progress=function(a,c){if(p){if(!0===c)throw Error("This deferred has already been fulfilled.");return g}b(n,0,a,null,q);return g};this.resolve=function(a,c){if(p){if(!0===c)throw Error("This deferred has already been fulfilled.");return g}b(n,p=1,k=a,null,q);n=null;return g};var r=this.reject=function(a,c){if(p){if(!0===c)throw Error("This deferred has already been fulfilled.");
return g}Error.captureStackTrace&&Error.captureStackTrace(l={},r);b(n,p=2,k=a,l,q);n=null;return g};this.then=g.then=function(a,b,e){var d=[e,a,b];d.cancel=g.cancel;d.deferred=new m(function(a){return d.cancel&&d.cancel(a)});p&&!n?c(d,p,k,l):n.push(d);return d.deferred.promise};this.cancel=g.cancel=function(b,g){if(p){if(!0===g)throw Error("This deferred has already been fulfilled.");}else{if(a){var c=a(b);b="undefined"===typeof c?b:c}h=!0;if(p){if(2===p&&k===b)return b}else return"undefined"===typeof b&&
(b=new e),r(b),b}};d(g)};m.prototype.toString=function(){return"[object Deferred]"};a&&a(m);return m})},"dojo/errors/CancelError":function(){define(["./create"],function(h){return h("CancelError",null,null,{dojoType:"cancel"})})},"dojo/errors/create":function(){define(["../_base/lang"],function(h){return function(l,e,f,a){f=f||Error;var d=function(b){if(f===Error){Error.captureStackTrace&&Error.captureStackTrace(this,d);var a=Error.call(this,b),k;for(k in a)a.hasOwnProperty(k)&&(this[k]=a[k]);this.message=
b;this.stack=a.stack}else f.apply(this,arguments);e&&e.apply(this,arguments)};d.prototype=h.delegate(f.prototype,a);d.prototype.name=l;return d.prototype.constructor=d}})},"dojo/promise/Promise":function(){define(["../_base/lang"],function(h){function l(){throw new TypeError("abstract");}return h.extend(function(){},{then:function(e,f,a){l()},cancel:function(e,f){l()},isResolved:function(){l()},isRejected:function(){l()},isFulfilled:function(){l()},isCanceled:function(){l()},always:function(e){return this.then(e,
e)},otherwise:function(e){return this.then(null,e)},trace:function(){return this},traceRejected:function(){return this},toString:function(){return"[object Promise]"}})})},"dojo/promise/instrumentation":function(){define(["./tracer","../has","../_base/lang","../_base/array"],function(h,l,e,f){function a(a,b,d){var c="";a&&a.stack&&(c+=a.stack);b&&b.stack&&(c+="\n    ----------------------------------------\n    rejected"+b.stack.split("\n").slice(1).join("\n").replace(/^\s+/," "));d&&d.stack&&(c+=
"\n    ----------------------------------------\n"+d.stack);console.error(a,c)}function d(b,c,d,e){c||a(b,d,e)}function b(a,b,d,e){b?f.some(k,function(b,c){if(b.error===a)return k.splice(c,1),!0}):f.some(k,function(b){return b.error===a})||k.push({error:a,rejection:d,deferred:e,timestamp:(new Date).getTime()});n||(n=setTimeout(c,m))}function c(){var b=(new Date).getTime(),d=b-m;k=f.filter(k,function(b){return b.timestamp<d?(a(b.error,b.rejection,b.deferred),!1):!0});n=k.length?setTimeout(c,k[0].timestamp+
m-b):!1}var k=[],n=!1,m=1E3;return function(a){var c=l("config-useDeferredInstrumentation");if(c){h.on("resolved",e.hitch(console,"log","resolved"));h.on("rejected",e.hitch(console,"log","rejected"));h.on("progress",e.hitch(console,"log","progress"));var f=[];"string"===typeof c&&(f=c.split(","),c=f.shift());if("report-rejections"===c)a.instrumentRejected=d;else if("report-unhandled-rejections"===c||!0===c||1===c)a.instrumentRejected=b,m=parseInt(f[0],10)||m;else throw Error("Unsupported instrumentation usage \x3c"+
c+"\x3e");}}})},"dojo/promise/tracer":function(){define(["../_base/lang","./Promise","../Evented"],function(h,l,e){function f(b){setTimeout(function(){d.apply(a,b)},0)}var a=new e,d=a.emit;a.emit=null;l.prototype.trace=function(){var b=h._toArray(arguments);this.then(function(a){f(["resolved",a].concat(b))},function(a){f(["rejected",a].concat(b))},function(a){f(["progress",a].concat(b))});return this};l.prototype.traceRejected=function(){var b=h._toArray(arguments);this.otherwise(function(a){f(["rejected",
a].concat(b))});return this};return a})},"dojo/promise/all":function(){define(["../_base/array","../Deferred","../when"],function(h,l,e){var f=h.some;return function(a){var d,b;a instanceof Array?b=a:a&&"object"===typeof a&&(d=a);var c,k=[];if(d){b=[];for(var h in d)Object.hasOwnProperty.call(d,h)&&(k.push(h),b.push(d[h]));c={}}else b&&(c=[]);if(!b||!b.length)return(new l).resolve(c);var m=new l;m.promise.always(function(){c=k=null});var s=b.length;f(b,function(a,b){d||k.push(b);e(a,function(a){m.isFulfilled()||
(c[k[b]]=a,0===--s&&m.resolve(c))},m.reject);return m.isFulfilled()});return m.promise}})},"dojo/when":function(){define(["./Deferred","./promise/Promise"],function(h,l){return function(e,f,a,d){var b=e&&"function"===typeof e.then,c=b&&e instanceof l;if(b)c||(b=new h(e.cancel),e.then(b.resolve,b.reject,b.progress),e=b.promise);else return 1<arguments.length?f?f(e):e:(new h).resolve(e);return f||a||d?e.then(f,a,d):e}})},"dojo/promise/first":function(){define(["../_base/array","../Deferred","../when"],
function(h,l,e){var f=h.forEach;return function(a){var d;if(a instanceof Array)d=a;else if(a&&"object"===typeof a){d=[];for(var b in a)Object.hasOwnProperty.call(a,b)&&d.push(a[b])}if(!d||!d.length)return(new l).resolve();var c=new l;f(d,function(a){e(a,c.resolve,c.reject)});return c.promise}})}}});define("frontend/layer/promise",[],1);
//@ sourceMappingURL=promise.js.map